# -----------------------------------------------------------------------------
# SITE VARIABLES
# -----------------------------------------------------------------------------

# This is a list of variables (Front Matter) to be throughout the site.
# ! Read more: http://jekyllrb.com/docs/frontmatter/

apply: open
# This can be open, or closed

social-media:
  500px:
  codepen:
  dribbble:
  email: info@stlartworks.org
  facebook: stlartworks
  flickr:
  github: stlartworks/
  instagram: stlartworks
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: stlartworks
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube:
  vimeo:


# -----------------------------------------------------------------------------
# THE ONLY WARNING!!!
# -----------------------------------------------------------------------------

# Do not use tabs in this configuration file! Only SPACES!!!
# This will either lead to parsing errors, or Jekyll will revert to the default settings. Use spaces instead.
# ! Read more: http://jekyllrb.com/docs/configuration/

# Use this YAML Lint tool to help: http://yamllint.com/
# YAML PARSER http://yaml-online-parser.appspot.com/

# -----------------------------------------------------------------------------
# YAML resources
# -----------------------------------------------------------------------------

# http://nodeca.github.io/js-yaml/
# http://yaml-online-parser.appspot.com/
# http://www.yamllint.com/

# -----------------------------------------------------------------------------
# LIQUID resources
# -----------------------------------------------------------------------------

# http://docs.shopify.com/themes/liquid-documentation/basics
# https://mobilecommons.zendesk.com/hc/en-us/articles/202052544-Liquid-templates


# -----------------------------------------------------------------------------
# SITE PERSONALIZATION
# -----------------------------------------------------------------------------

name: St. Louis Artworks
# This text will be used on the homepage to personalize the name of your site
# This will also act as a text link that always points to the homepage

tagline: Creating. Opportunities.
# This will show up in the header next to the site logo
#Job training for young creatives


# -----------------------------------------------------------------------------
# GOOGLE ANALYTICS
# -----------------------------------------------------------------------------

google_analytics: UA-795125-1
# This will enable Google Analytics to track your site


# -----------------------------------------------------------------------------
# POST Settings
# -----------------------------------------------------------------------------

#future: false
# This will hide future dated posts from your live blog.

# show_drafts: false

# -----------------------------------------------------------------------------
# PAGINATION (not working right now)
# -----------------------------------------------------------------------------

#paginate: 5
#paginate_path: "/blog/page:num"
# Use pagination on the blog page to better manage posts

# -----------------------------------------------------------------------------
# COMMENTS
# -----------------------------------------------------------------------------

disqus: stlartworks
# To enable comments, use your Disqus "shortname" to enable comments
# You can create a free acount here: https://disqus.com/


# -----------------------------------------------------------------------------
# SITE CONFIGURATION
# -----------------------------------------------------------------------------

url: http://stlartworks.org

# http://stlartworks.github.io
# http://repoName.github.io
# http://www.yourDomainName.com
# This will confiure your sitemap.xml and RSS feed

baseurl: ""
# use this configuraiton for a "Username" or "Organization" site
# ex: http://userName.github.io

# else

# baseurl: "/repoName"
# use this configuraiton for a "Project" site:
# ex: http://userName.github.io/REPO-NAME

# ! Ream more: http://blog.parkermoore.de/2014/04/27/clearing-up-confusion-around-baseurl/


timezone: America/Chicago
# Set the timezone. ! Read more: http://jekyllrb.com/docs/configuration/




# -----------------------------------------------------------------------------
# COLLECTIONS
# -----------------------------------------------------------------------------

#  team_members:
#    output: true
#    permalink: /team-members/:path/

# Not everything is a post or a page. Maybe you want to document the various methods in your open source project, members of a team, or talks at a conference. Collections allow you to define a new type of document that behave like Pages or Posts do normally, but also have their own unique properties and namespace.

# Read more: http://jekyllrb.com/docs/collections/
# Read more: http://www.sitepoint.com/getting-started-jekyll-collections/

# collections:
#   apprentices:
#     output: true
#
#   board:
#     output: true
#
#   instructors:
#     output: true
#
#   programs:
#     output: true
#
#   sponsors:
#     output: true
#
#   staff:
#     output: true



# -----------------------------------------------------------------------------
# DEFAULT FRONT MATTER SETTINGS
# -----------------------------------------------------------------------------

# Using YAML Front Matter is one way that you can specify configuration in the pages and posts for your site.

# ! Read more: http://jekyllrb.com/docs/configuration/

# Just setting default layouts for several collections( or post-types in WP lingo)

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  # -
  #   scope:
  #     path: ""
  #     type: "apprentices"
  #   values:
  #     layout: "apprentices"
  # -
  #   scope:
  #     path: ""
  #     type: "board"
  #   values:
  #     layout: "board"
  # -
  #   scope:
  #     path: ""
  #     type: "instructors"
  #   values:
  #     layout: "instructors"
  # -
  #   scope:
  #     path: ""
  #     type: "sponsors"
  #   values:
  #     layout: "sponsors"
  # -
  #   scope:
  #     path: ""
  #     type: "staff"
  #   values:
  #     layout: "staff"


# -----------------------------------------------------------------------------
# SAFE PLUGINS allowed by gitHub pages
# -----------------------------------------------------------------------------

gems:
# Plugin list
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  # - jekyll-mentions
  # - jekyll-redirect-from


# -----------------------------------------------------------------------------
# PERMALINK SETTINGS
# -----------------------------------------------------------------------------

permalink: /:title/
# These may only apply to posts, not to pages, collections or static files.
# ! Read more: http://jekyllrb.com/docs/permalinks/


# -----------------------------------------------------------------------------
# CONVERSION SETTINGS
# -----------------------------------------------------------------------------

highlighter: rouge
# Pygments is a generic syntax highlighter for general use in all kinds of software such as forum systems, wikis or other applications that need to prettify source code.

# Read more: http://pygments.org/

markdown: kramdown
# kramdown (sic, not Kramdown or KramDown, just kramdown) is a free MIT-licensed Ruby library for parsing and converting a superset of Markdown.

# Read more: http://kramdown.gettalong.org/


# -----------------------------------------------------------------------------
# SAFE MODE
# -----------------------------------------------------------------------------

safe: true
# Use "true" if you intend to let gitHub automatically build your pages

# GitHub Pages is powered by Jekyll, however all Pages sites are generated using the --safe option to disable custom plugins for security reasons. Unfortunately, this means your plugins won’t work if you’re deploying to GitHub Pages.

#You can still use GitHub Pages to publish your site, but you’ll need to convert the site locally and push the generated static files to your GitHub repository instead of the Jekyll source files.

# ! Read more: http://jekyllrb.com/docs/plugins/


# -----------------------------------------------------------------------------
# Serving
# -----------------------------------------------------------------------------

# port: 1111
# Change port if you are working on multiple Jekyll sites at once

# -----------------------------------------------------------------------------
# PRODUCITON BUILD SETTINGS
# -----------------------------------------------------------------------------

exclude:
# Exclude (ignore) these files in your Producion build

  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - .editorconfig
  - .jshintrc
  - LICENSE
  - README.md
  - vendor
  - .travis.yml


# Check GitHub Dependency Verison: https://pages.github.com/versions/
